common: &common
  adapter: postgresql
  username: postgres
  password: root # from psql setup, see Postgresql
  encoding: utf8
  pool: 5
  host: localhost
  port: 5432

development:
  <<: *common
  database: myapp_development

test:
  <<: *common
  database: myapp_test

production:
  <<: *common
  database: myapp_production